CREATE TABLE QUESTIONNAIRE_DESCRIPTION (
    QUESTIONNAIRE_ID INT,
    ACTIVE NUMBER(1),
    PRIMARY KEY (QUESTIONNAIRE_ID)
);

CREATE TABLE QUESTION_DESCRIPTION (
    QUESTION_ID INT,
    QUESTIONNAIRE_ID INT,
    ACTIVE NUMBER(1),
    MULTI_ANSWER NUMBER(1),
    REFERENCE_QUESTIONNAIRE INT,
    PRIMARY KEY (QUESTION_ID),
    FOREIGN KEY (QUESTIONNAIRE_ID) REFERENCES QUESTIONNAIRE_DESCRIPTION(QUESTIONNAIRE_ID)
);

CREATE TABLE ANSWER_DESCRIPTION (
	ANSWER_ID INT,
    QUESTION_ID INT,
    ACTIVE NUMBER(1),
    MULTI_ANSWER NUMBER(1),
    PRIMARY KEY (ANSWER_ID),
    FOREIGN KEY (QUESTION_ID) REFERENCES QUESTION_DESCRIPTION(QUESTION_ID)
);

CREATE TABLE CONTENT (
	USER_ID VARCHAR(255),
    QUESTION_ID INT,
    ANSWER_ID INT,
    REFERENCE_QUESTIONNAIRE INT,
    FOREIGN KEY (QUESTION_ID) REFERENCES QUESTION_DESCRIPTION(QUESTION_ID),
    FOREIGN KEY (REFERENCE_QUESTIONNAIRE) REFERENCES QUESTIONNAIRE_DESCRIPTION(QUESTIONNAIRE_ID)
);

CREATE INDEX IDX_USER_QUESTION ON CONTENT (USER_ID, QUESTION_ID);
